# enable automatic backup 
db.backup.enabled=true

# time to perform backup in UTC
db.compact.time=10:10:10

# backup interval in hours
db.backup.interval=24

# keep backup for number of days 
db.backup.day.limit=7

# enable database compacting (not recommended)
db.compact.enabled=false

# day to perform compacting
db.compact.day=1

# time to perform compacting in UTC
db.compact.time=11:11:11

# compacting interval in hours
db.compact.interval=168

