# Lines starting with # are comments.

# The timezone in which the times are expressed in the received schedule files.
# Default value: UTC
# Examples: JST, UTC, AST
# Accepted values: all timezone ids supported by Java (a list is provided here http://tutorials.jenkov.com/java-date-time/java-util-timezone.html)
# timezone = UTC

default_language = eng

# The numbering of columns in the file starts from 1.
title_column = 2

# A value of 9999 assigned to short_description_column means that 
# the short synopsis will not be read from the file, but left empty. 
short_description_column = 3

# A value of 9999 assigned to extended_description_column means that 
# the extended synopsis will not be read from the file, but left empty.
extended_description_column = 143

# A value of 9999 assigned to language_column means that the
# language will not be read from the file, but the default_language will be used.
language_column = 149

# title_2_column = 9999

# short_description_2_column = 9999

# extended_description_2_column = 9999

# language_2_column = 9999

# genre_column = 9999

# parental_rating_column = 9999


