#--- Saved 19/08 04:43:07 ---
#Wed Aug 19 04:43:07 UTC 2026
redundancy.server=10.0.0.2
discovery.ttl=1
discovery.port=50111
redundancy.startup.state=INACTIVE
redundancy.max.primary.retries=4
primary.port=50112
redundancy.timeout=1000
primary.server=239.0.0.2
redundancy.startup.role=STANDBY
discovery.server=239.0.0.1
redundancy.port=50110
redundancy.max.retries=4
redundancy.enabled=true
