# Lines starting with # are comments.
# After this file is changed, a restart of the BarrowaEPG service is required.
# The servers where the triggers should be forwarded are defined like this: server1=192.168.27.178. Uncomment the next lines and replace x.y.z.t with the IPs you want to forward the triggers to. Multiple servers can be defined, but only one per line.
#server1=x.y.z.t
#server2=a.b.c.d
